### PR TITLE
Fixed compilation issues on Linux

### PR DESCRIPTION
**Pull request by orangeduck**
The ordering of the compile and linker flags was causing trouble for gcc on Linux - talking about undefined references to all of the OpenCV stuff.

Also seems -arch is an invalid flag on gcc.

Hope these fixes do not conflict with compilation on OSX.

Thanks for the awesome software!

### CODE REVIEW

**Comment by ajdroid** [comment]
It worked alright for me. I don't think changes are necessary

**Comment by kylemcdonald** [comment]
thanks @ajdroid, going to close this since it's been a while and i haven't heard any other complaints.

**Comment by ajdroid** [comment]
Hey @kylemcdonald great job maintaining this. The way the makefiles are set up, it helped me cross compile and run this on embedded systems very easily. So thanks for that. 
Sorry, I know this isn't the appropriate forum for this, but do you know of a good head pose estimator to use with your code?

**Comment by kylemcdonald** [comment]
hey @ajdroid for head pose estimation the values are in `_clm._pgolbl`. here is an example of extracting them: https://github.com/kylemcdonald/ofxFaceTracker/blob/master/src/ofxFaceTracker.cpp#L259-L260

**Comment by ajdroid** [comment]
From context, I'm guessing these are the Euler angles(?) Is there any documentation about the `_pglobl` object?

**Comment by kylemcdonald** [comment]
they are euler angles, and there is no further documentation other than their usage in ofxFaceTracker (which has a higher-level API than FaceTracker itself does, based on discussion with jason)

**Pull request closed without merging**
